project.template.yaml
spec_diffs/3010

The previous 3002 spec version is now 3010, this is to give the 4.0.x
chain versions space to upgrade

feat: 🎸 Update to support 4.1.1 chain version

---

src/mappings/mappingHandlers.ts

Tooling GQL expects snake case for call_id
Reverts the values to what they were [before](https://github.com/PolymathNetwork/polymesh-subquery/compare/v4.1.0-s1...v5.0.0#diff-cacfd1ec0155919c9a4ad17775cce37b7d92a736f89d84216e087d8f19405385L132)
Note the column names remain snake case in the DB despite the entity field being camel case.

fix: 🐛 Revert to using snake case in extrinsics table

---

docker-compose.yml
docker-entrypoint.sh

By setting the HTTP endpoint for the chain we can dynamically get the
chain id needed for SubQuery
By setting `NETWORK_HTTP_ENDPOINT` SubQuery can dynamically figure out the chain id. Without this chain it will be cumbersome to use with polymesh_local, or any other ephemeral dev chain.
Its possible to get this info over ws, but from a script its a bit harder. Also with this way we won't infer it by mistake in production environments.

feat: 🎸 Allow for dynamic lookup of NETWORK_CHAIN_ID

---

src/mappings/serializeLikeHarvester.ts

Type value for `Ticker` was changed to `PolymeshPrimitivesTicker` with 5.0.0 upgrade and subquery missed serialising objects for this type. Added the check for the new type as well along with the old type.
DA-371

fix: 🐛 serialize ticker for type `PolymeshPrimitivesTicker`

---

src/mappings/entities/mapTickerExternalAgentHistory.ts

While create `AgentGroupMembership`, the attribute `groupId` was incorrectly referred to as `group` causing the following error 
```
ERROR:  null value in column "group_id" violates not-null constraint
```
This change corrects the name mismatch.
[DA-386](https://polymath.atlassian.net/browse/DA-386)

fix: 🐛 Correct `AgentGroupMembership.groupId` attribute name

---

schema.graphql
src/mappings/generatedColumns.ts
tests/unit/generatedColumns.test.ts

The claim events on the chain were having varied casing for attribute names. 
For example, wrt staging environment, block [56926](https://polkadot.js.org/apps/#/explorer/query/56296) was having snake case for attributes as below - 
But for the block [923906](https://polkadot.js.org/apps/#/explorer/query/923906) (, attribute names were camelCase as shown below - 
It seems this is after the v14 metadata. Polkadot says - 
> Be aware that in the JS version naming defaults to camelCase where names of fields in Substrate defaults to snake_case. (Each version aligning with conventions in the respective languages)
**Changelog** 
* This change makes sure that while fetching any attribute values from event both cases are checked for to support backward compatibility with old blocks from 4.0.0 node …

fix: 🐛 Handle camelCase for structure keys and add deprecated enum values

---

schema.graphql

Fixes the error: 
"ailed to index block at height 384889 handleCall() SequelizeDatabaseError: invalid input value for enum public_enum_0bf3c7d4ef: "add_exempted_entities"

fix: 🐛 add_exempted_entities as enum

---

src/mappings/generatedColumns.ts
tests/unit/generatedColumns.test.ts

`extractValue` method was returning undefined for key value `0`. (Found out via block [30594](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstaging-rpc.polymesh.live#/explorer/query/30594) in staging). 
Fixed the logic to return 0

fix: 🐛 Fix `extractValue` method to handle `0` value

---

schema.graphql
scripts/diff_versions.ts
spec_diffs/2021-2023
spec_diffs/5000000-5000999
src/chainTypes/5.x.x.json
src/mappings/entities/mapIdentities.ts

* Schema for secondary keys was changed for 5.x.x chain due to which block #925160 was failing in staging. 
`signer: Signatory` is replaced by `key: AccountId`
* Fixed the `diff_versions` script and updated them
* Replaced `to: Identity` to `toId: String` in `Authorization` schema

fix: 🐛 Correct parsing of address for secondary accounts and update Authorization entity

---

db/migration.ts
schema.graphql
src/mappings/generatedColumns.ts
src/mappings/mappingHandlers.ts
src/mappings/util.ts
tests/entities/__snapshots__/assetDocuments.test.ts.snap
tests/entities/__snapshots__/assets.test.ts.snap

* Fix parsing of document attributes, caId, distribution values 
* Updated the AssetDocument entity to support JSON field for content hash
Type of `AssetDocument.contentHash` is now changed from `String` to json `ContentHash`
[DA-253](https://polymath.atlassian.net/browse/DA-253)

fix: 🐛 Fix parsing of various types after 5.0.0 upgrade

---

schema.graphql
src/mappings/entities/mapCompliance.ts
src/mappings/entities/mapIdentities.ts
src/mappings/entities/mapPortfolio.ts
src/mappings/entities/mapSettlement.ts
src/mappings/mappingHandlers.ts
src/mappings/util.ts

* While creating instructions, receiver DID/Portfolio isn't validated. To support this scenario, SQ inserts apt portfolio which isn't present (without any name). For this if the underlying DID is also not present, it creates one without any primaryAccount(sets the value to `''`). 
This was found in mainnet block - [1375280](https://polymesh.subscan.io/block/1375280?tab=event)
* Fix parsing of Asset compliances for `AssetComplianceReplaced` event.
N/A
[DA-253](https://polymath.atlassian.net/browse/DA-253)

chore: 🤖 Support unvalidated DID while creating legs

---

src/mappings/entities/mapAuthorization.ts
src/mappings/entities/mapExternalAgentAction.ts
src/mappings/entities/mapSto.ts
src/mappings/mappingHandlers.ts
src/mappings/util.ts

With latest SQ sync, ticker values are not properly serialized and are getting stored in hex format.
- The `serializeLikeHarvester` function wasn't able to return the serialized values for tickers since the meta-type was being received as `[u8;12]` instead of `Ticker`. To get the exact type name, `meta.fields` is now being used.
- Fixed the parsing issue of `offering_asset` for `sto.FundraiserCreated` event. [Staging block - [1765423](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstaging-rpc.polymesh.live#/explorer/query/1765423)]
- Handles missing `fromId` for `Authorization` when `identity.cdd_register_did` is invoked. This particular case occurs
when secondary keys are also passed as params along with target account. [Mainnet block - …

fix: 🐛 Handle ticker serialization with metadata v14

---

src/mappings/entities/mapClaim.ts

With testnet block [1746733](https://polymesh-testnet.subscan.io/block/1746733?tab=event), claim added event was triggered with a non-existing target DID. Since the target claim isn't validated before depositing the event, this PR adds a check to make sure the identity exists.
NA
DA-253

fix: 🐛 Handle identity state when claim added

---

schema.graphql
src/mappings/entities/mapBridgeEvent.ts
src/mappings/entities/mapIdentities.ts
src/mappings/entities/mapPortfolio.ts
tests/entities/portfolios.test.ts

Adds a `deletedAt` attribute to `Portfolio` entity which now gets populated when a portfolio is deleted, instead of removing the entity. This is to prevent the deletion of all other entities referencing the deleted Portfolio
DA-253

fix: 🐛 Testnet native graphql sync issues

---

schema.graphql
src/mappings/entities/mapAsset.ts
src/mappings/entities/mapPortfolio.ts
src/mappings/entities/mapProposal.ts
src/mappings/entities/mapSettlement.ts
src/mappings/util.ts
tests/entities/__snapshots__/assets.test.ts.snap
tests/entities/assets.test.ts

- `AssetCreated` event now also emits `funding_round` and `identifiers`.
This updates them while asset creation
- Also, handles the `Byte` type funding round name and asset name
- Ignores `AssetTransfer` case when tokens are redeemed
- With chain version 5.0.0 lot of types were converted to `Bytes`, which
it handles now correctly
- Also, adds `memo` to the `PortfolioMovement` entity
- Fixes missing `funding_round` values for older chains (< 5.1.0)
NA
DA-432, DA-433

Changes to support chain 5.1.0 new features

---

src/mappings/util.ts

With 5.1.0 chain, the variant Custom(CustomClaimTypeId) was added to enum ClaimType. This changes how polkadot reads in the value for ClaimTypes. Earlier while parsing the exemptKey, it used to read the types as string values such as `Accredited`, but now it reads them as json values `{"accredited": null}`. This PR modifies the logic for parsing the exemptKey
NA
NA

fix: 🐛 Fix parsing of claim type in exempt keys

---

db/migrations/8.4.2.sql
package.json
schema.graphql

This removes non-null constraint from
`TickerExternalAgentAction.callerId` to handle scenario where checkpoint is created via scheduler
Fixes the testnet issue for block 5871710 where checkpoints are created via scheduler
```
2022-11-22T09:38:34.892Z <fetch> INFO fetch block [5871710,5871809], total 100 blocks 
2022-11-22T09:38:36.767Z <sandbox> ERROR Received an error in handleEvent while handling the event 'checkpoint.CheckpointCreated': SequelizeValidationError: notNull Violation: TickerExternalAgentAction.callerId cannot be null
at InstanceValidator._validate (/usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/instance-validator.js:50:13)
```
NA
DA-466

fix: 🐛 Drop non-null constraint from `TickerExternalAgentAction.callerId`

---

.github/workflows/docker-image.yml

[PR-98](https://github.com/PolymeshAssociation/polymesh-subquery/pull/98/files#diff-2bc030495cca422df1d48626427d805b36039015ab13ca4b2bdaea23affa1f33) moved `Dockerfile` -> `/docker/sq-Dockerfile` The build plugin defaults to `Dockerfile`, but lets us specify the location: with `file`. [Docs](https://github.com/docker/build-push-action#customizing)
- uncovered in: [DA-464](https://polymesh.atlassian.net/browse/DA-464) 
- introduced in: [DA-401](https://polymesh.atlassian.net/browse/DA-401)
It wasn't uncovered in the initial merge since it was marked as a `chore` which semver bot skips

fix: 🐛 specify dockerfile location for github actions

---

docker-compose.yml
package.json

Sometimes docker fails to start and errors as follows - 
```
Step 11/11 : USER subquery
---> Running in 9e9957f585b2
Removing intermediate container 9e9957f585b2
---> dd7ccfd29456
Successfully built dd7ccfd29456
Successfully tagged polymesh-subquery_subquery-node:latest
Pulling graphql-engine (onfinality/subql-query:latest)...
latest: Pulling from onfinality/subql-query
ca7dd9ec2225: Already exists
6fb1b25da510: Pull complete
7604515c95e1: Pull complete
e6bf7dff8d85: Pull complete
738cd76cfa5e: Pull complete
59981c69dea0: Pull complete
Digest: sha256:6b8e2dc9db1bff423e4c177e96b88c97974f9bfdb40e104e33a1488bcb2c6fd6
Status: Downloaded newer image for onfinality/subql-query:latest
Creating polymesh-subquery_postgres_1 ... done
Creating polymesh-subquery_subquery-node_1 ... done
ERROR: for …
```

fix: 🐛 Add `start_period` to node container to fix startup issue

---

docker-compose.yml
docker/docker-entrypoint.sh

`disable-historical` is now always true, as there are issues enabling it. `timestamp-field` is always passed since its expected to have `created_at` timestamps on all records
None. the args were supposed to be passed as the values they are now hard coded to, and passing the same argument twice didn't throw an error when I tried.

feat: 🎸 hardcode certain Subquery command flags

---

db/migrations/8.5.04.sql
package.json
schema.graphql

As of now, chain doesn't validate the Legs to have a valid Asset ticker. This will be handled in on of the chain's future releases. To solve this now, we are dropping the foreign key constraint on the asset attribute of Leg entity. 
This problem was found in block 6101310 on testnet, erring as follows - 
```
2022-12-13T12:28:25.053Z <sandbox> ERROR Received an error in handleEvent while handling the event 'settlement.InstructionCreated': Error
at Query.run (/usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
at /usr/local/lib/node_modules/@subql/node/node_modules/sequelize/lib/sequelize.js:313:28
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async PostgresQueryInterface.upsert …
```

fix: 🐛 Drop foreign key constraint for `Leg.assetId`

---

db/migrations/8.4.3.sql

There was an error in the legacy stat query which I fixed and pushed directly into master by mistake ([fix: 🐛 Query fix in legacy stat script](https://github.com/PolymeshAssociation/polymesh-subquery/commit/75e7bb3a99cdf12d8fde3a222c2924b052457d83)). Adding the change with fix commit to bump up the version 
NA
NA

fix: 🐛 Query fix in legacy stat script

---

db/migrations/8.4.3.sql
scripts/run-sql.ts

Currently, if there were any SQL errors in the migration queries the errors were not being known while adding them. Exiting the process on any such error will let us track these mistakes when tests are run.
NA
DA-475

fix: 🐛 Throw on migration query errors

---

.github/workflows/docker-image.yml

This removes the warning `The "save-state" command is deprecated and will be disabled soon. Please upgrade to using Environment Files.` while building and pushing docker image
Reference job link - https://github.com/PolymeshAssociation/polymesh-subquery/actions/runs/3639617801/jobs/6144319522
NA
DA-459

ci: 🎡 Update docker github actions to latest version

---

Jenkinsfile
README.md
deploy/.env.template
deploy/Dockerfile
deploy/build.sh
deploy/push.sh
deploy/run.sh

- adds basic jenkins build pipeline
currently the container [image](https://hub.docker.com/layers/polymeshassociation/polymesh-subquery/v9.0.0/images/sha256-09b509005bd99f94788edbfbae264a9afa7450a26b0d97603c104126f7cba3cc?context=explore) for `polymeshassociation/polymesh-subquery:v9.0.0` does not support `linux/arm64`, however, the upstream [image](https://hub.docker.com/layers/onfinality/subql-node/v1.13.3/images/sha256-322e4794c04a67715cd63a79ba2214f46cab5d646b2fe22f24c7f3ec434b1bae?context=explore) for `onfinality/subql-node:v1.13.3` does; this PR makes builds for `linux/arm64` available under a private registry, for testing
- adds distinct `Dockerfile` for arm64 builds; this could be considered for merging with the one located @ `docker/sq-Dockerfile`
- fixes docs - running with …

jenkins build pipeline

---

db/migrations/9.2.02.sql
package.json
src/mappings/util.ts

StoStatus is processed differently for older chains. This PR makes changes to handle both cases and also makes changes in migration file to handle the same.
(Noticed this in testnet and mainnet old blocks)
NA
DA-522

fix: 🐛 Handle STO status correctly for chain < 5.0.0

---

db/migrations/9.2.02.sql
package.json

When bumping versions non-incrementally, migration 9.2.02.sql throws error that `public_enum_9ceea16a44` is missing. 
In case of incremental bumping of version, it gets automatically created. Added in migration to handle both cases
NA
DA-522

fix: 🐛 Add `StoStatus` with migration

---

package.json
release.config.js
yarn.lock

`@semantic-release/npm` only updates the package version but doesn't commit it. Using `@semantic-release/git` we can create a chore commit to add it to the git repo.
NA
DA-762

feat: 🎸 Use semantic-release/git to commit package version

---

db/migrations/1_migration_entity.sql
db/migrations/3_polyx_transactions_entity.sql

In a scenario where someone hasn't executed migration 1,2,3 and directly updates to latest alpha, SQ was erring that it couldn't find `processed_block` column in `migrations` table. To fix that, this PR adds the newly added columns of the migration entity in previous migrations as well. Those who may have executed the latest alpha successfully, won't be affected by this.

fix: 🐛 Update queries to correctly create "migrations"

---

src/mappings/entities/mapPolyxTransaction.ts

Before spec version 5000000, `TreasuryDisbursement` didn't have the target account ID. This uses the primary key of the target DID in those scenarios.

fix: 🐛 Handle missing address in treasury disbursement event

---

.gitignore
schema.graphql
src/mappings/entities/mapIdentities.ts

This adds a new entity `ChildIdentity` which save the mapping between a parent and child Identity. We can inversely query the children using the `children` field in `Identity` entity
NA
DA-887

feat: 🎸 Add support for child identities

---

src/mappings/util.ts

lookup custom asset types to provide type string instead of JSON with ID. `Asset.type` returns the name. Previously would return a JSON string that encoded an ID, which would require an additional call to chain to lookup.

fix: 🐛 custom fungible asset types

---

schema.graphql
src/mappings/entities/mapClaim.ts
src/mappings/entities/mapCustomClaimType.ts
src/mappings/entities/mapEvent.ts
src/mappings/generatedColumns.ts
tests/unit/generatedColumns.test.ts

- saves CustomClaimType as an Entity
- if Claim has customClaimTypeId -> but that is not yet synced to SQ -> it will be created
- allows querying for all the created CustomClaimType(s)
https://polymesh.atlassian.net/browse/DA-909

feat: 🎸 save customClaimType as entity

---

db/migrations/1_consts_for_6_0_1_chain.sql
schema.graphql

Add new extrinsics and events for 6.1 chain support. 
Following are the new extrinsics added -  
```
instantiate_with_code_as_primary_key
instantiate_with_hash_as_primary_key
allow_identity_to_create_portfolios
revoke_create_portfolios_permission
create_custody_portfolio. 
```
Following are the new events added - 
```
RemoveAssetAffirmationExemption
AssetAffirmationExemption
PreApprovedAsset
RemovePreApprovedAsset
PreApprovedPortfolio
RevokePreApprovedPortfolio
InstructionAutomaticallyAffirmed. 
```
NA
DA-940

feat: 🎸 Add new events and extrinsics for 6.1 chain support

---

db/migrations/2_populate_instruction_to_asset_transaction.sql
db/migrations/3_fix_asset_transaction_event.sql
src/mappings/entities/mapAsset.ts
src/mappings/entities/mapIdentities.ts
src/mappings/entities/mapNfts.ts
src/mappings/util.ts

For new fungible asset transfer events (since chain 6.x), the asset transaction entry was adding in the event as `Transfer` for Issued/Redeemed cases. Also for NFT related transactions `IssedNFT` and `RedeemedNFT` weren't being used. This fixes the logic to correctly populate the event value.
NA
DA-967

fix: 🐛 Correctly populate the event value for AssetTransaction

---

db/migrations/4_add_extrinsic_for_issued_txs.sql
src/mappings/entities/mapAsset.ts
src/mappings/entities/mapEvent.ts
src/mappings/entities/mapNfts.ts

In case of `ControllerTransfer` as the reason for `NFTPortfolioUpdate` event, asset transaction entry was being made but NFTHolder set of nft_ids was not getting updated. This handles the logic to  update the NFTHolders
NA
DA-969

fix: 🐛 Handle NFT holders in case of `nft.controller_transfer`

---

.github/workflows/main.yml

This changes the semantic bot release user to polymesh-bot and configures git to sign the release commits and tags.
N/A
N/A
N/A

feat: 🎸 add ssh signing to the release bot configuration

---

src/mappings/entities/mapAsset.ts
src/mappings/entities/mapPolyxTransaction.ts
src/mappings/entities/mapSettlement.ts
src/mappings/entities/mapStatistics.ts

Since the spec version value for PP chain was reset to 1000000, the logic around a few features got botched. Using the specName from runtimeVersion, logic has been modified to fix the features.
NA
DA-1154

fix: 🐛 Handle spec version logic correctly for private chain

---

src/mappings/entities/mapAsset.ts
src/mappings/entities/mapExtrinsic.ts

improves block processing time for large batch transactions by removing serializeCallArgsLikeHarvester when saving extrinsics. Before a batch of 400 issue NFTs would take minutes to process, with this change it now takes seconds. It does change the format of `Extrinsic.params` and `Extrinsic.paramsTxt`. If you are using these fields a full resync is reccomended, and to update any code accessing any nested params. It still returns a JSON serializable string.
BREAKING CHANGE: 🧨 Extrinsic.params and Extrinsic.paramsTxt have updated their JSON format
✅ Closes: [DA-1162](https://polymesh.atlassian.net/browse/DA-1162)
**Example**
Previous params:
```json
[{"name":"dest","value":"0xda7743ce00715c8076b80c16aa04632a90909c259c529cfdd4cad07524c80a71"},{"name":"value","value":1}]
```
New params: …

feat: 🎸 improve block process time for large batch transactions

---

src/mappings/entities/mapEvent.ts
src/mappings/entities/mapIdentities.ts
src/mappings/entities/mapPolyxTransaction.ts
src/mappings/mappingHandlers.ts
src/mappings/util.ts

removes dependency on Event, Extrinsic and Block within the handlers
These were for migrations, which we shouldn't need to run. By making sure there is no accidental coupling to the Blocks/Events we should have more flexibility in how we process.
There is no foreign key constraint on `Blocks` and the query service handles the null case, so if we know there is know dependency then its safe to process them in parallel.

refactor: 💡 remove Event/Extrinsic/Block dependency

---

src/mappings/entities/mapBlock.ts
src/mappings/mappingHandlers.ts

skip recreating already indexed extrinsics
locally, reduces staging block 1010260 sync time from ~33 seconds to ~10 seconds.

refactor: 💡 improve sync performance on large batches

---

docker-compose.yml
package.json
src/mappings/entities/assets/mapStatistics.ts

custom claims added in chain v5.1.0 caused claimType enum to be serialized into object instead of string

fix: 🐛 historical stat type enum handling

---

package.json
project.ts
schema.graphql
src/mappings/entities/assets/mapAsset.ts
src/mappings/entities/assets/mapCompliance.ts
src/mappings/entities/assets/mapCorporateActions.ts
src/mappings/entities/assets/mapNfts.ts
src/mappings/entities/assets/mapStatistics.ts
src/mappings/entities/assets/mapTransferManager.ts
src/mappings/entities/externalAgents/mapExternalAgent.ts
src/mappings/entities/externalAgents/mapExternalAgentAction.ts
src/mappings/entities/externalAgents/mapExternalAgentHistory.ts
src/mappings/entities/identities/mapClaim.ts
src/mappings/entities/identities/mapPortfolio.ts
src/mappings/entities/stos/mapSto.ts
src/utils/assets.ts
src/utils/portfolios.ts
src/utils/stos.ts
src/utils/transferManagers.ts
yarn.lock

- Portfolio movements incorrectly had ticker value populated against asset ID field for Non Fungible tokens. This fixes the issue. (DA-1327)
- Adds new events and extrinsics from latest 7.x chain (DA-1333)
- Add new handler for mapping event `TickerUnlinkedFromAsset` (DA-1333)
- Update logic of asset ID generation for legacy tickers (to generate valid UUID) (DA-1333)
- Bump `@polymeshassociation/polymesh-types` to `5.14.0` (DA-1331)
NA
DA-1327, DA-1333, DA-1331

Add new events for 7.x chain and some other fixes
