PolymeshAssociation/polymesh-subquery

compat.sql
Drop/remove the creation of custom data views
DA-275
=> chore: 🤖 Remove views

src/mappings/util.ts
Handle null string to be able to sync with testnet
=> Handle null string

schema.graphql
Adds a new event I missed on the previous PR
=> feat: 🎸 Add CustomClaimTypeAdded to EventIdEnum

schema.graphql
Adds missing extrinsic to the list
N/A
N/A
=> fix: 🐛 add update_venue_signers extrinsic

LICENSE, README.md, package.json
Add Apache 2.0 license. Mentions that SubQuery itself is also under the same license
None
[DA-460](https://polymesh.atlassian.net/browse/DA-460)
=> chore: 🤖 add Apache 2.0 license

.github/CODEOWNERS, db/migrations/8.5.06.sql, package.json, schema.graphql
This drops the callerId null constraint in alpha
NA
NA
=> Master into alpha

db/migrations/9.2.01.sql, package.json, schema.graphql
This adds new NFT pallet, its new extrinsics and events to existing enums.
NA
DA-554
=> feat: 🎸 Add new pallet, extrinsics, events for 5.3.0 chain

db/migrations/9.2.02.sql, db/migrations/9.2.03.sql, package.json, schema.graphql
There were two more asset pallet extrinsics which weren't mentioned in the 5.3.0rc-1 changelog. Added them to CallIdEnum
NA
DA-554
=> feat: 🎸 Add new asset pallet extrinsics to enum

spec_diffs/5002000-5002009, spec_diffs/5003000-5003009, src/chainTypes/5.2.x.json, src/chainTypes/5.3.x.json, src/chainTypes/index.ts
Add types spec for 5.2.x and 5.3.x chain
NA
NA
=> feat: 🎸 Add chain types for 5.2.x and 5.3.x

schema.graphql
Adds GraphQL comments that should show up in explorers.
None
[DA-617](https://polymesh.atlassian.net/browse/DA-617)
This adds GraphQL doc comments. It should make it a little bit easier to for users.
[DA-617]: https://polymesh.atlassian.net/browse/DA-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: ✏️ add GraphQL documents for better a developer experience

yarn.lock
Bump deps to resolve security alerts
NA
DA-542
=> fix: 🐛 Bump resolved dependencies

db/migrations/9.2.06.sql, schema.graphql
⚠️ instances must include this update to process 5.4 blocks
✅ Closes: [DA-639](https://polymesh.atlassian.net/browse/DA-639)
[DA-639]: https://polymesh.atlassian.net/browse/DA-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add 5.4 chain events

package.json
bump the package.json version so the migrations run
=> feat: 🎸 bump version to 9.6.0 to trigger migrations

db/schemaMigrations.ts
CI was failing due to unpushed changes.
=> fix: 🐛 Remove sq version insert at start

docker/docker-entrypoint.sh, src/mappings/migrations/migrationHandlers.ts
updates HTTP log in entrypoint.sh and doesn't log for 0 migrations being ran
=> feat: 🎸 skip log when no migrations run

.dockerignore, .gitignore, db/migrations/5_add_new_extrinsics_6_0_4_chain.sql, schema.graphql
Adds missing extrinsics to `CallIdEnum`
```
affirm_with_receipts_with_count
affirm_instruction_with_count
reject_instruction_with_count
withdraw_affirmation_with_count
```
NA
DA-899
=> feat: 🎸 Add new settlement extrinsics to `CallIdEnum`

docker/sq-Dockerfile, schema.graphql, src/mappings/entities/common.ts, src/mappings/entities/mapAsset.ts, src/mappings/entities/mapCompliance.ts, src/mappings/entities/mapNfts.ts, src/mappings/entities/mapPortfolio.ts, src/mappings/entities/mapSettlement.ts, src/mappings/mappingHandlers.ts, src/mappings/util.ts
Add `isNftCollection` to `Asset`. Add `NftHolder` entity. `Identity` now has `heldNfts` field. `Leg`, `PortfolioMovement` and `AssetTransaction` now have `nftIds`. `amount` is now nullable for these entities
BREAKING CHANGE: 🧨  `amount` is now nullable for `Leg`, `PortfolioMovement` and `AssetTransaction`
✅ Closes: [DA-905](https://polymesh.atlassian.net/browse/DA-905)
[DA-905]: https://polymesh.atlassian.net/browse/DA-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 Map NFT events

db/migrations/1_consts_for_6_1_0_chain.sql, db/migrations/2_add_deleted_proposal_status.sql, db/migrations/3_update_multisig_proposal_status.sql, project.template.ts, schema.graphql, src/mappings/entities/mapChainUpgrade.ts, src/mappings/entities/mapMultiSig.ts, src/mappings/mappingHandlers.ts
- In case of `ProposalExecuted` event for multisigs, use the boolean parameter to update the status to `Success` or `Failure`
- In case of major chain upgrades, set all the active proposals as `Deleted`
NA
DA-933, DA-938
=> fix: 🐛 Handle MultiSig proposal status correctly

db/migrations/1_add_as_derivative_call.sql, schema.graphql
Adds `as_derivative` extrinsic call to `CallIdEnum` list
NA
NA
=> feat: 🎸 Add `as_derivative` to `CallIdEnum`

db/migrations/2_populate_instruction_to_asset_transaction.sql, db/migrations/3_fix_asset_transaction_event.sql, db/migrations/4_add_extrinsic_for_issued_txs.sql, package.json, schema.graphql, src/mappings/entities/mapAsset.ts, src/mappings/entities/mapEvent.ts, src/mappings/entities/mapIdentities.ts, src/mappings/entities/mapNfts.ts, src/mappings/util.ts
=> Merge all gitea changes to develop

db/migrations/5_add_6_2_support.sql, schema.graphql
chain 6.2 introduces instruction mediators. this adds the required events so that blocks containing these events can be processed
None. (old versions will break without the patch!)
✅ Closes: DA-1044
=> feat: 🎸 add 6.2 calls and events

db/migrations/6_add_asset_mediators.sql, schema.graphql, src/mappings/entities/mapAsset.ts, src/mappings/entities/mapSettlement.ts, src/mappings/util.ts
Tracks required mediators for assets
None
✅ Closes: DA-1025
=> feat: 🎸 add tracking for asset required mediators

package.json, yarn.lock
Bump polymesh-types package
None
=> chore: 🤖 bump polymesh types package

schema.graphql, src/mappings/entities/mapSettlement.ts
Tracks pending instruction mediators and their affirmation status
None
✅ Closes: [DA-1100](https://polymesh.atlassian.net/browse/DA-1100)
[DA-1100]: https://polymesh.atlassian.net/browse/DA-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 track pending instruction mediators

project.template.ts, schema.graphql, src/mappings/entities/mapAsset.ts
track asset pre-approvals for assets
None
[DA-1080](https://polymesh.atlassian.net/browse/DA-1080)
[DA-1080]: https://polymesh.atlassian.net/browse/DA-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 track asset pre-approvals

project.template.ts
Tests are unable to catch on github CI because of a missing event. This is already present in develop branch. 
NA
NA
=> test: 💍 Resolve failing tests issue

db/migrations/1_proposal_failed.sql, db/migrations/2_state_trie_migration.sql, db/schemaMigrations.ts, docker-compose.yml, docker/docker-entrypoint.sh, project.template.ts, schema.graphql
add tracking for a new event added in 6.3. Updates migration script to work with historical state enabled. Also adds statetriemigration pallet and extrinsic
None
[DA-1180](https://polymesh.atlassian.net/browse/DA-1180)
[DA-1180]: https://polymesh.atlassian.net/browse/DA-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 add `ProposalFailedToExecute` event and `statetriemigration` pallet

db/migrations/1_proposal_failed.sql, db/migrations/2_state_trie_migration.sql, db/schemaMigrations.ts, docker-compose.yml, docker/docker-entrypoint.sh, project.template.ts, schema.graphql
=> Release 6.3 events 

src/mappings/entities/mapAsset.ts
speeds up resync of historical assets by parallelizing rpc calls
locally this take staging block 56300 time from 1:15 to 0:47, and its sibling blocks roughly the same.
The promise cost is negligible for future blocks, but this should shave a few minutes every resync so I think its worth it.
=> perf: ⚡️ batch async mapAsset calls

project.template.ts, src/mappings/entities/mapIdentities.ts, src/mappings/entities/mapPolyxTransaction.ts, src/mappings/mappingHandlers.ts, src/mappings/util.ts
avoid unnecessary promises and move some handlers to be ran on a per block basis. Also adds an explicit `handleGenesis` function
=> refactor: 💡 make getEventParams sync + add genesisHandler

.github/workflows/authenticate-commits.yml, .github/workflows/fast-forward.yml
Add github actions to 
- authenticate commits via `MIDDLEWARE_ALLOWED_SIGNERS` list 
- fast forward PR merging
NA
DA-1216
=> ci: 🎡 Add actions for authenticate and fast forward commits

src/mappings/util.ts
Correctly ignore offchain legs. It failed on staging block - [11202679](https://staging-app.polymesh.dev/?rpc=wss%3A%2F%2Fstaging-rpc.polymesh.dev%2F#/explorer/query/11202679)
=> fix: 🐛 Correctly ignore offchain legs

package.json, src/mappings/entities/mapSettlement.ts
use optimized batch function for leg updates
✅ Closes: DA-1219
=> perf: ⚡️ use `store.batch(Insert|Update)` for legs

db/compat.sql, db/migrations/1_proposal_failed.sql, db/migrations/2_state_trie_migration.sql, db/migrations/3_extrinsic_hex_prefix.sql, db/schemaMigrations.ts, docker/docker-entrypoint.sh, docker/sq-Dockerfile, package.json, src/mappings/entities/mapAsset.ts, tests/unit/serializeLikeHarvester.test.ts, yarn.lock
update subquery dependency to the latest version. This resolves an issue where bulkUpdate would not work when workers were enabled
BREAKING CHANGE: 🧨 `updated_at` field removed from tables
[DA-1236](https://polymesh.atlassian.net/browse/DA-1236)
[DA-1236]: https://polymesh.atlassian.net/browse/DA-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: 🎸 update SubQuery to the latest version

db/migrations/2_move_funds.sql, package.json
Migration file was not added for the CA move funds related change - https://github.com/PolymeshAssociation/polymesh-subquery/pull/246.
This adds the event and extrinsic for the same
NA
DA-1235
=> fix: 🐛 Add migration to add move funds related event/extrinsic

package.json
=> chore: 🤖 bump package.json version to 17.1.0

schema.graphql, src/mappings/entities/assets/mapAsset.ts, src/mappings/entities/assets/mapCompliance.ts, src/mappings/entities/assets/mapCorporateActions.ts, src/mappings/entities/assets/mapNfts.ts, src/mappings/entities/block/mapExtrinsic.ts, src/mappings/entities/common.ts, src/mappings/entities/confidentialAssets/mapConfidentialAccountCreated.ts, src/mappings/entities/confidentialAssets/mapConfidentialAsset.ts, src/mappings/entities/confidentialAssets/mapConfidentialAssetTransaction.ts, src/mappings/entities/confidentialAssets/mapConfidentialTransaction.ts, src/mappings/entities/events/mapBridgeEvent.ts, src/mappings/entities/events/mapEvent.ts, src/mappings/entities/events/mapStakingEvent.ts, src/mappings/entities/externalAgents/mapExternalAgent.ts, src/mappings/entities/externalAgents/mapExternalAgentAction.ts, src/mappings/entities/externalAgents/mapExternalAgentHistory.ts, src/mappings/entities/identities/mapAuthorization.ts, src/mappings/entities/identities/mapClaim.ts, src/mappings/entities/identities/mapIdentities.ts, src/mappings/entities/identities/mapPortfolio.ts, src/mappings/entities/multiSig/mapMultiSig.ts, src/mappings/entities/multiSig/mapMultiSigProposal.ts, src/mappings/entities/settlements/mapSettlement.ts, src/mappings/entities/stos/mapSto.ts, src/mappings/migrations/genesisHandler.ts, src/utils/events.ts
=> Link events
